version: "3.9"
services:
  db-literature:
    image: postgres:16.3
    container_name: db-literature
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db-literature
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alura.com
      PGADMIN_DEFAULT_PASSWORD: admin.alura
